# --- CONEXÃO BANCO DE TESTE (H2 EM MEMÓRIA) ---
#spring.datasource.url=jdbc:h2:mem:ajudavcdb_test;DB_CLOSE_DELAY=-1;MODE=MySQL
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# Define a plataforma específica para o H2 trabalhar interpretando comandos padrão MySQL
#spring.sql.init.mode=never

# Mostra no console os comandos SQL executados em tempo real
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
# Opcional: Reduzir ruído de avisos de metadados
#logging.level.org.hibernate.orm.jdbc=ERROR   
server.address=0.0.0.0
server.port=8055